language: ruby
sudo: false
cache:
  bundler: true
  yarn: true
notifications:
  email: false
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install node
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  # Install Yarn dependencies
  - yarn

  # Setup the database
  - psql -c 'CREATE DATABASE unicarona_test' -U postgres
  - bundle exec rake db:test:prepare
script:
  - bundle exec rspec --format progress --no-profile
